### ISSUE TITLE
🥵

### ISSUE THREAD

**Issue by JohnsonLi** [jiayang/cs2124#1]
![01g2hk12fmt21](https://user-images.githubusercontent.com/23644630/74078173-e8837a80-49f4-11ea-9592-f4f0010df037.gif)

**Comment by jiayang** [comment]
Please do not comment irrelevant things on my repositories, NON-master ELO town of salem-er.

**Comment by JohnsonLi** [comment]
> Please do not comment irrelevant things on my repositories, NON-master ELO town of salem-er.

[a](https://youtu.be/Tff2PBatf2Y)

**Comment by JohnsonLi** [comment]
> 
> 
> > Please do not comment irrelevant things on my repositories, NON-master ELO town of salem-er.


> [a](https://youtu.be/Tff2PBatf2Y)
 [a](https://youtu.be/Tff2PBatf2Y)  [a](https://youtu.be/Tff2PBatf2Y)  [a](https://youtu.be/Tff2PBatf2Y)
